version: 2
jobs:
  build:
    docker:
      - image: circleci/python

    steps:
      - checkout
      - run:
          name: Pull Submodules
          command: |
            git submodule update --init --recursive
      - run:
          name: Installing GCC, CMake, Ninja, Protobuf
          command: sudo apt-get update && sudo apt-get install -y gcc g++ cmake ninja-build protobuf-compiler
      # Use cached mlir installation if possible.
      - restore_cache:
          key: V2-LLVM-PROJECT-{{ arch }}
      - run:
          name: Install MLIR
          command: |
            # Check whether cache restoration succeeds by checking whether
            # mlir-opt executable exists.
            if [ ! -f llvm-project/build/bin/mlir-opt ]; then
              export MAKEFLAGS=-j4
              source .circleci/install-mlir.sh
            fi
      - save_cache:
          key: V2-LLVM-PROJECT-{{ arch }}
          paths:
            - llvm-project
      - run:
          name: Install ONNF
          command: |
            mkdir build && cd build
            LLVM_PROJ_SRC=$(pwd)/../llvm-project/ LLVM_PROJ_BUILD=$(pwd)/../llvm-project/build cmake ..
            make all
            LIT_OPTS=-v make check-mlir-lit
      - run:
          name: Print the Current Time
          command: date
